# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_books', '0006_auto_20170629_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(to='my_books.Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_books.Publisher'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
