# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0007_auto_20170704_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
        migrations.AlterField(
            model_name='profile',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_books.Publisher'),
        ),
    ]
