# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0008_auto_20170706_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
