# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0011_auto_20170706_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='pen_name',
            field=models.CharField(max_length=100),
        ),
    ]
