# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0012_auto_20170706_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='pen_name',
            field=models.CharField(max_length=100, verbose_name='author name'),
        ),
    ]
