# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0008_auto_20170706_1333'),
        ('my_books', '0013_auto_20170706_2316'),
    ]

    operations = [
    ]
