# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0013_auto_20170706_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
